version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.6.5

    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install -j4 --path vendor/bundle
      - run: bundle exec rspec
